POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{"username":"reyiz", "email": "armo@gmail.com","password": "12345"}  


###
GET http://localhost:3000/users/650332abf1c6b7d678264a8d HTTP/1.1
###

DELETE http://localhost:3000/users/6502e5d2cfd8dccea5673e03 HTTP/1.1

###
PATCH http://localhost:3000/users/650332d6f1c6b7d678264c0c HTTP/1.1
content-type: application/json

{"username": "KAGAN"}

###
POST http://localhost:3000/books HTTP/1.1
content-type: application/json

{ "title": "TOTO", "author": "ALAR MARTİNEZ", "genre": "Fantasy" }

###
DELETE  http://localhost:3000/books/64f5c9407feae6989037e9b8 HTTP/1.1

###
GET  http://localhost:3000/books/64f3347294f54bfa5355a5b4 HTTP/1.1

###
PATCH http://localhost:3000/books/65083d9c519997e9a568c679 HTTP/1.1
content-type: application/json

{"title": "GOTGOTGOT"}
###

POST http://localhost:3000/users/650332abf1c6b7d678264a8d/ownBookToUser HTTP/1.1
content-type: application/json

{"bookId": "650848e813a1a291eed38e05"}
###
DELETE http://localhost:3000/users/650332d6f1c6b7d678264c0c/removeBookFromUser HTTP/1.1
content-type: application/json

{"bookId": "650848e813a1a291eed38e05"} 

###
POST http://localhost:3000/users/650332d6f1c6b7d678264c0c/addReviewToBook HTTP/1.1
content-type: application/json

{"bookId": "650848e813a1a291eed38e05",
    "review": "Çok iyi bir kitaptıı."  }